services:
  - type: web
    name: kairos
    env: python
    buildCommand: "./build.sh"
    startCommand: "bash -c \"python manage.py migrate --noinput && gunicorn todou_ai.wsgi:application\""
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 1