databases:
  - name: kairos-db
    databaseName: kairos
    user: kairos

services:
  - type: web
    name: kairos
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn todou_ai.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kairos-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4